apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "exampleresources.examplecrd.jasonhancock.com"
spec:
  group: "examplecrd.jasonhancock.com"
  scope: "Namespaced"
  names:
    plural: "exampleresources"
    singular: "exampleresource"
    kind: "ExampleResource"
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - color
            - size
            properties:
              color:
                type: string
              size:
                type: string
